config/routes.rb
SampleApp::Application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root to: 'static_pages#home'

  match '/o-nas',
    to: 'static_pages#about',
    as: "about"
  match '/o-nas/naszautorskiprogram',
    to: 'static_pages#authorprogram',
    as: "autorski"
  match '/o-nas/pedagogika',
    to: 'static_pages#pedagogika',
    as: "pedagogika"
  match '/o-nas/kadra',
    to: 'static_pages#kadra',
    as: "kadra"
  match '/o-nas/adaptacja',
    to: 'static_pages#adaptacja',
    as: "adaptacja"

  match '/strefarodzica',
    to: 'static_pages#parentsite'

  match '/plandnia',
    to: 'static_pages#dayplan'

  match '/oplaty',
    to: 'static_pages#pricelist'

  match '/galeria',
    to: 'static_pages#gallery'

  match '/kontakt',
    to: 'static_pages#contact',
    as: "contact"

  match '/rejestracja',
    to: 'users#new'
  match '/zaloguj',
    to: 'sessions#new',
    as: "signin"
  match '/wyloguj',
    to: 'sessions#destroy',
    via: :delete,
    as: "signout"

  match '/pomoc',
    to: 'static_pages#help',
    as: "help"

  match '/skontaktuj-sie-z-nami',
    to: 'contact#new',
    as: 'contact_us',
    via: 'get'

  match '/skontaktuj-sie-z-nami',
    to: 'contact#create',
    as: 'contact_us',
    via: 'post'

end

app/controllers/static_pages_controller.rb
# encoding: utf-8

# -*- encoding : utf-8 -*-
class Time
  def before? input_time
    (self <=> input_time) == -1
  end
end

class StaticPagesController < ApplicationController

  def home
    if signed_in?
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
    @wpisowe = Time.now.before? Date.new(Time.now.year,4,30)
    @dzienotwarty = Time.now.before? Date.new(Time.now.year,4,6)
  end

  def about
  end

  def authorprogram
  end

  def pedagogika
    @folder = "../docs-monte"
    @files = Array.new
    @files << [ "Chlonny_umysl_2010_2011.pdf", "Chłonny umysł" ]
    @files << [ "Faza_wrazliwa_dla_porzadku.pdf", "Faza wrazliwa dla porządku" ]
    @files << [ "f_sensytywn_na_ruch.pdf", "Faza sensytywna na ruch" ]
    @files << [ "Normalizacja.pdf", "Normalizacja" ]
    @files << [ "obserwacja_w_przygotowanym_otoczeniu_Krakow.pdf", "Obserwacja w przygotowanym otoczeniu" ]
    @files << [ "PIM-Fazy_senytywne_Warszawa_2010.pdf", "Fazy sensytywne" ]
    @files << [ "Przygotowane_otoczenie.pdf", "Przygotowane otoczenie" ]
    @files << [ "Rola_nauczyciela_montessorianskiego.pdf", "Rola nauczyciela montessorianskiego" ]
    # @files << [ "Trzygodzinna_praca_wlasna_DW.pdf", "Trzygodzinna praca własna" ]
    @files << [ "CASA_DEI_BAMBINI.pdf", "Casa dei Bambini" ]
  end

  def kadra
  end

  def adaptacja
  end

  def parentsite
    @folder = "docs"
    @files = Array.new
    @files << [ "Statut Żłobka Kubusiowy Raj w Bobrowcu.doc", "Statut Żłobka" ]
    @files << [ "Procedura-przyprowadzania-i-odbierania-dzieci.docx", "Procedura przyprowadzania i odbierania dzieci"]
    @files << [ "Umowa-o-przyjęcie-dziecka.docx", "Umowa o przyjęcie dziecka" ]
    @files << ["Upoważnienie-do-odbioru-dziecka.rtf", "Upoważnienie do odbioru dziecka"]
    @files << ["Regulamin.pdf", "Regulamin" ]
    @files << ["karta informacyjna dziecka.docx", "Karta informacyjna dziecka" ]
  end

  def dayplan
  end

  def pricelist
  end

  def gallery
  end

  def contact
  end

  def help
  end

end

app/helpers/static_pages_helper.rb
# -*- encoding : utf-8 -*-
module StaticPagesHelper
end

app/views/static_pages/_aboutheader.html.haml
%header.navbar.up
  %nav
    %ul.nav
      -# %li= menu_link_to 'static_pages', 'authorprogram',
        "Nasz Autorski Program Edukacyjny",
        autorski_path
      %li= menu_link_to 'static_pages', 'about',
        "Nasze podejście",
        about_path
        -# "Informacje o Nas",
      %li= menu_link_to 'static_pages', 'pedagogika',
        "Więcej o pedagogice Montessori",
        pedagogika_path
        -# Pedagogika Montessorii",

      -# %li= menu_link_to 'static_pages', 'kadra',
        "Kadra",
        kadra_path
      -# %li= menu_link_to 'static_pages', 'adaptacja',
        "Adaptacja",
        adaptacja_path

app/views/static_pages/about.html.haml
- description ''
- keywords ''

= render 'aboutheader'

.hero-unit#page-about

  %h1= title 'O nas'

  %h2 Co warto o nas wiedzieć

  %p „Kubusiowy Raj” jest niepublicznym żłobkiem edukacyjnym z elementami pedagogiki Marii Montessori. Zapewniamy dociekliwym istotkom w wieku niemowlęcym i poniemowlęcym (od 5 miesiąca do 3 roku życia) opiekę pełną troskliwości, uśmiechu i cierpliwości, a także mądrą stymulację i szansę na kreatywny rozwój.

  %p Zatrudniamy wykwalifikowany personel, odpowiednio przygotowany do pełnienia tak odpowiedzialnej funkcji, jaką jest towarzyszenie Państwa pociechom w odkrywaniu siebie i świata.

  %p Zapewniamy Państwa pociechom zdrowe, smaczne posiłki. Śniadania, drugie śniadania i podwieczorki przygotowuje Nasza Ciocia Grażynka, zaś dwudaniowe obiady dowożone są przez sprawdzony catering. Uwzględniamy wszelkie wskazania dietetyczne.
  %p
    Realizujemy
    =link_to "program edukacyjny", autorski_path
    który w sposób uwzględniający prawidła rozwojowe, jak również indywidualne predyspozycje Państwa pociech, stymuluje, uczy, pobudza do eksplorowania świata. Proponujemy dzieciom codzienne czytanie mądrych bajek, zabawy paluszkowe i aktywności plastyczne, stymulujące motorykę małą, jak również ćwiczenia muzyczno- ruchowe z elementami integracji sensorycznej. W codzienne zajęcia wplatamy także słowa zaczerpnięte z języka angielskiego. Wiemy bowiem, jak chłonne są umysły Państwa pociech.
  %p
    Potrafimy  jednak znaleźć
    %q złoty środek
    między odpoczynkiem, mądrą stymulacją, zabawą swobodną i kierowaną.

  %p U nas dzieci odpoczną, swobodnie się pobawią, oczywiście pod naszym czujnym okiem, a także rozwiną ukryty w nich potencjał.

  %p Stwarzamy Maluchom odpowiednie warunki do nabywania umiejętności w zakresie samoobsługi, świadomości własnego ciała.

  -# %p Uczynimy wszystko, by, ani Państwa Dzieci nie zanudzić, ani nie przestymulować. U nas dzieci odpoczną, swobodnie się pobawią, oczywiście pod naszym czujnym okiem, a także rozwiną ukryty w nich potencjał.

  %p Wiemy, że Maluszki potrzebują głównie ciepła, poczucia bezpieczeństwa, cierpliwości, a ponad wszystko otwartości na wysyłane przez nich sygnały.
  %p
    Uwielbiamy obserwować dzieci podczas swobodnej zabawy, bo taka obserwacja to kopalnia wiedzy o ich potrzebach, predyspozycjach, fascynacjach, mocnych i słabych stron. Zdobyte taką drogą informacje stanowią dla nas bazę do indywidualizowania oddziaływań wychowawczych i edukacyjnych.
  %p Współpracujemy z instruktorem rytmiki, logopedą i psychologiem.

  %p.lead
    Zastanawiają się Państwo, jak można
    %q kształcić
    takie małe istotki? Jak mogą wyglądać zajęcia dla takich maluchów? Już śpieszymy z odpowiedzią.

  %p
    Odpowiednio zaaranżowaliśmy otaczającą je przestrzeń. Wyposażyliśmy ją w
    %q mądre zabawki
    \, zachęcające do dociekania, odkrywania prawideł metodą
    %q prób i błędów
    \. Codziennie zapoznajemy je z dostosowanymi do ich możliwości i wieku, piosenkami i wierszykami, w których przemycamy słówka angielskie . Natomiast naturalny w tym wieku głód ruchu maluchy zaspokajają podczas harców na dużym, odpowiednio przystosowanym i kreatywnie wyposażonym placu zabaw.
    -# \,  Wdrażamy w życie autorski program edukacyjny, zapoznający dzieci z bogactwem otaczającego świata (więcej o programie w zakładce
    -#= succeed ")." do
      =link_to "nasz autorski program edukacyjny",
    -# Codziennie proponujemy dzieciom proste, całkowicie bezpieczne eksperymenty fizyczno- chemiczne, zapoznajemy je z dostosowanymi do ich możliwości i wieku, piosenkami i wierszykami, w których
    -# %q przemycamy słówka francuskie i angielskie
    \. Natomiast naturalny w tym wieku
    %q głód ruchu
    maluchy zaspokajają podczas harców na dużym, odpowiednio przystosowanym i kreatywnie wyposażonym placu zabaw.
  %p Pobudzamy dzieci do doskonalenia umiejętności  z zakresu samoobsługi, samodzielności, do odkrywania swoich potrzeb emocji, uczymy współistnienia w grupie rówieśniczej, uwrażliwiamy na kontakty z naturą i drugim człowiekiem.
  %p
    Nie zapominamy także o kojącej muzyce, która towarzyszy maluchom zarówno podczas zabawy, jak i zasypiania. Wierzymy bowiem, iż
    %q Muzyka jest stenografią uczuć
    i
    %q balsamem dla duszy
    \. U nas Państwa pociechy będą słuchać muzyki z różnych stron świata, śpiewać, tańczyć, akompaniować na wykonanych przez siebie bębenkach i grzechotkach.
  %p
    Codziennie zapraszamy także maluchy w fascynującą podróż do świata bajek,  bo
    %q Książka - to mistrz, co darmo nauki udziela, kto ją lubi - doradcę ma i przyjaciela, który z nim smutki dzieli, pomaga radości, chwilę nudów odpędza, osładza cierpkości
    \.

app/views/static_pages/adaptacja.html.haml
- description ''
- keywords ''

= render 'aboutheader'

.hero-unit#page-about

  %h1= title 'Adaptacja'

  -# %h2 --coś dostawić--

  %p Wiemy, jak trudno Maluchom rozstać się z ukochanymi Rodzicami, proponujemy zatem łagodną adaptację. Przez pierwszy tydzień pobytu Państwa pociech w naszym żłobku zapraszamy na zajęcia także Państwa. Pozwalamy, by Państwo sami zdecydowali, jak przebiegać będzie proces rozłąki Państwa z maluszkami. Oczywiście, chętnie wesprzemy Państwa radą i wskazówkami.

app/views/static_pages/authorprogram.html.haml
- description ''
- keywords ''

= render 'aboutheader'

.hero-unit#page-about

  %h1= title 'Nasz Autorski Program Edukacyjny'

  %h2 Na czym on dokładnie polega?

  %p W naszym żłobku tydzień podzieliśmy na dni tematyczne:
  %table.program
    %thead
      %tr
        %th Dzień tygodnia
        %th Nazwa
    %tr
      %td(width="200px") Poniedziałek
      %td Dzień Zwierząt
    %tr
      %td Wtorek
      %td Dzień Kolorów
    %tr
      %td Środa
      %td Dzień Roślin
    %tr
      %td Czwartek
      %td Dzień Świadomości własnego ciała
    %tr
      %td Piątek
      %td Dzień przedmiotów znanych i nieznanych

  %p Każdego dnia proponujemy Państwa pociechom zajęcia ruchowe, muzyczne, językowe i plastyczne, związane z danym pojęciem. Przygotowując nasz program, czerpaliśmy z psychologii rozwojowej i naszych zawodowych doświadczeń. Ufamy,że w taki sposób wzbogacimy wiedzę Państwa pociech o świecie, rozwiniemy ich zmysły, a także pobudzimy ich rozwój językowy, ruchowy i poznawczy.

  %p
    = succeed '.' do
      Bliskie nam jest przesłanie Pedagogiki M. Montessorii, z której czerpiemy inspirację do codziennych działań wychowawczo-edukacyjnych. Więcej o Pedagogice M. Montessorii odnajdą Państwo w zakładce
      = link_to "Pedagogika M. Montessorii", pedagogika_path

app/views/static_pages/contact.html.haml
- description ''
- keywords ''

.hero-unit#page-contact

  %h1= title 'Kontakt'


  %h2 Telefony

  #box-map
    <iframe width="400" height="400" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q&source=s_q&hl=pl&geocode=&q=Mazowiecka+24,+Bobrowiec,+Polska&aq=0&oq=mazowiecka+24,&sll=52.063256,20.974059&sspn=0.015461,0.038581&t=h&ie=UTF8&hq=&hnear=Mazowiecka+24,+05-502+Bobrowiec,+piaseczy%C5%84ski,+Mazowieckie,+Polska&ll=52.060077,20.967321&spn=0.005277,0.008562&z=16&output=embed&iwloc=near"></iframe>
    %p.pull-right <a href="https://maps.google.com/maps?f=q&source=embed&hl=pl&geocode=&q=Mazowiecka+24,+Bobrowiec,+Polska&aq=0&oq=mazowiecka+24,&sll=52.063256,20.974059&sspn=0.015461,0.038581&t=h&ie=UTF8&hq=&hnear=Mazowiecka+24,+05-502+Bobrowiec,+piaseczy%C5%84ski,+Mazowieckie,+Polska&ll=52.060077,20.967321&spn=0.005277,0.008562&z=16&iwloc=near" style="color:#0000FF;text-align:left">Wyświetl większą mapę</a>
    -# <iframe width="400" height="400" src="https://maps.google.com/maps?f=q&source=s_q&hl=pl&geocode=+&q=mazowiecka+24,+bobrowiec&ie=UTF8&hq=&hnear=Mazowiecka+24,+05-502+Bobrowiec,+piaseczy%C5%84ski,+Mazowieckie,+Polska&t=m&ll=52.059404,20.966806&spn=0.012665,0.027466&z=15&output=embed&iwloc=near" frameborder="0" marginwidth="0" marginheight="0" scrolling="no"></iframe>

  #left
    -#%p
      %strong{display: "inline"} Masz pytanie?
      = link_to "Skontaktuj się z nami! <i class=\'icon-envelope\'></i>".html_safe,
      contact_us_path,
      id: "contact_link"

    %address
      %p
        %strong Kubusiowy Raj Konrad Zawiślak <br>
        ul. Mazowiecka 24 <br>
        05-502 Bobrowiec

      %p
        %strong Dyrektor
        tel. 881 589 599

      %p
        %strong.tab Właściciel
        tel. 505 106 699

      %p
        %strong.tab e-mail:
        %strong <a href="mailto:biuro@zlobekkubusiowyraj.pl">biuro@zlobekkubusiowyraj.pl</a>

      %p
        %strong
        = link_to "Formularz kontaktowy <i class=\'icon-envelope\'></i>".html_safe,
          contact_us_path,
          id: "contact_link"

      -# Formularz kontaktowy

      %p
        %strong.tab NIP:
        123-102-01-15

      %p
        %strong.tab REGON:
        146001443

      %p
        %strong.tab Nr konta:
        13 1950 0001 2006 0279 0756 0002
        Bank: IDEA BANK S.A.


  -#
    .pull-right
      <iframe width="400" height="400" src="https://maps.google.com/maps?f=q&source=s_q&hl=pl&geocode=+&q=mazowiecka+24,+bobrowiec&ie=UTF8&hq=&hnear=Mazowiecka+24,+05-502+Bobrowiec,+piaseczy%C5%84ski,+Mazowieckie,+Polska&t=m&ll=52.059404,20.966806&spn=0.012665,0.027466&z=15&output=embed" frameborder="0" marginwidth="0" marginheight="0" scrolling="no"></iframe>

    .row.span5
      .row
        %address.span5
          %p
            %strong Kubusiowy Raj Konrad Zawiślak <br>
            ul. Mazowiecka 24 <br>
            05-502 Bobrowiec


        %p
          %strong Dyrektor
        %p tel. 881 589 599

        -#.row
        %p
          %strong Właściciel
        %p tel. 505 106 699


        -#.row
        %p
          %strong e-mail:
        %p
          %strong <a href="mailto:biuro@zlobekkubusiowyraj.pl">biuro@zlobekkubusiowyraj.pl</a>

        -# Formularz kontaktowy

        -#.row
        %p
          %strong NIP:
        %p
          123-102-01-15
        -#.row
        %p
          %strong REGON:
        %p
          146001443

      .row
        %p
          %strong Nr konta:
        %p.justify
          13 1950 0001 2006 0279 0756 0002
      %p.span
        Bank: IDEA BANK S.A.

app/views/static_pages/dayplan.html.haml
- description 'Plan zajęć żłobka'
- keywords    'plan, zajęcia, plan zajęć'

.hero-unit#page-dayplan

  %h1= title 'Plan Dnia'

  %h2 To co twoje pociechy (&hellip;)

  -# %em Na poranną toaletę przyszedł czas
  -# %em Kto potrzebuje, do łazienki maszeruje
  -#%em Nasza gimnastyka dla dzielnego smyka

  -#%style{:type => "text/css"}
    :sass
      ul
        display: none

  %table.plan
    %th Początek
    %th Koniec
    %th Opis aktywności
    %tr
      %td 6.45
      %td 7.45
      %td
        %em Przygodę w Kubusiowym Raju czas zacząć
        %ul
          %li przyjmowanie dzieci, indywidualne kontakty z rodzicami,
          %li.self zabawa dzieci w kącikach zainteresowań,
          -# %li.monte Montessoriańska Praca Własna,
          -# %li.monte Lekcja Ciszy
    %tr
      %td 7.45
      %td 8.00
      %td
        %em Wszystkie dzieci są już z nami i do śniadanka zasiadamy
        -# %ul
          %li.toilet toaleta
    %tr
      %td 8:00
      %td 8.30
      %td
        %em Nasze Kubusiowe śniadanko
        %ul
          %li.eat śniadanie
    %tr
      %td 8.30
      %td 9.00
      %td
        %em Po śniadaniu umyć ząbki to dobrego dnia są początki
        %ul
          %li.toilet toaleta poranna
    %tr
      %td 9.00
      %td 9.30
      %td
        %em Piosenką się witamy i do wspólnej zabawy zapraszamy
        %ul
          %li.group przywitanie
    %tr
      %td 9.30
      %td 10.00
      %td
        %em Teraz troszkę się pouczymy, a przy okazji świetnie pobawimy
        %ul
          %li.group zajęcia edukacyjne w kręgu.
    %tr
      %td 10.00
      %td 10.30
      %td
        %em Drugie śniadanie to nasze do podwórkowych harców przygotowanie
        %ul
          %li.eat drugie śniadanie
    %tr
      %td 10.30
      %td 11.30
      %td
        %em Hej ho, hej ho - na nasz plac zabaw by się szło
        %ul
          %li.group zabawa na świeżym powietrzu
    %tr
      %td 11.30
      %td 12.00
      %td
        %em Do naszego żłobka wracamy - szatnię i toaletę odwiedzamy
        %ul
          %li.toilet toaleta
    %tr
      %td 12.00
      %td 12.30
      %td
        %em Zupkę chętnie zjemy i do snu się szykujemy
        -# %em Na obiadową ucztę przyszedł czas
        %ul
          %li.eat obiad - pierwsze danie
    %tr
      %td 12.30
      %td 14.30
      -#%td 14.30
      %td
        %em Odpoczywamy i przy muzyce słodko zasypiamy
        %ul
          %li.sleep popołudniowa drzemka
    %tr
      %td 14.30
      %td 15.00
      %td
        %em Na obiadową ucztę przyszedł czas
        -# %em Po śnie jeść się nam chce
        %ul
          %li.eat obiad - drugie danie
    %tr
      %td 15.00
      %td 15.30
      %td
        %em Kto potrzebuje do łazienki maszeruje
        %ul
          %li.toilet toaleta popołudniowa
          -# %li.eat podwieczorek
    %tr
      %td 15.30
      %td 16.30
      %td
        %em Na zabawę przyszedł czas
        %ul
          %li.group zabawy tematyczne
    %tr
      %td 16.30
      %td 17.00
      %td
        %em Teraz szybko tu sprzątniemy i do podwieczorku usiądziemy
        %ul
          %li.eat podwieczorek
    %tr
      %td 17.00
      %td 18.00
      %td
        %em Teraz posprawdzamy jakie zabawki w sali jeszcze mamy i na Naszych Kochanych rodziców cierpliwie poczekamy
        -# %em Na popołudniową zabawę mamy teraz czas - porysujemy, potańczymy, pośpiewamy, posprawdzamy, jakie zabawki w Sali mamy i na naszych kochanych rodziców cierpliwie poczekamy.
        %ul
          -# %li.monte Montessoriańska Praca Własna,
          -# %li.monte Lekcja Ciszy,
          %li.self Zabawy swobodne w kącikach zainteresowań
          %li.group Aktywność plastyczna, gry i zabawy tematyczne

app/views/static_pages/help.html.haml
- description ''
- keywords ''

.hero-unit#page-other
  %h1= title 'Pomoc'
  %p
    Skontaktuj się z nami przez
    = link_to "formularz", contact_us_path
    kontaktowy lub telefonicznie.

app/views/static_pages/home.html.haml
- description 'Żłobek Kubusiowy Raj w Boborowcu. Działamy na terenie Bobrowca i z uśmiechem świadczymy usługi dla okolicznych miejscowości takich jak Piaseczno, Bobrowiec, Wilcza Góra, Kolonia Lesznowola, Łoziska, Zalesie Dolne, Gołków, Bąkówka, Robercin'
- keywords 'Bobrowiec, Piaseczno, Wilcza góra, Władysławów, Żłobek, opieka, dziecko, zabawa, nauka, dzieci'

= display_meta_tags site: "Żłobek Kubusiowy Raj"

.hero-unit#page-home
  - if signed_in?
    .row
      %aside.span4
        %section
          = render 'shared/user_info'
        %section>
          = render 'shared/stats'
        %section
          = render 'shared/micropost_form'
      .span8
        %h3 Micropost Feed
        = render 'shared/feed'

  - else
    -# %h1 Wkrótce otwarcie!
    -#%h2 Pierwsza trójka zapisanych dzieci bez wpisowego!

    - if @dzienotwarty then
      %h1 Zapraszamy na adaptacyjny dzień otwarty!
      %h2
        Następny już w sobotę 6 kwitnia od 10<sup>00</sup> do 16<sup>00</sup>
        %br
        Zapraszamy dzieci wraz z rodzicami.

    - else
      %h1 Witamy na stronie naszego żłobka!
      %h2
        Prowadzimy zajęcia według autorskiego programu wychowania opartego na doświadczeniach Marii Montessorii.

    .center
      = link_to "Sprawdź jak dojechać".html_safe, contact_path, class: "btn btn-large btn-primary"

      -#= link_to "Zarejestruj się!", rejestracja_path, class: "btn btn-large btn-primary"
      = link_to "Skontaktuj się z nami!", contact_us_path, class: "btn btn-large btn-primary"

    - if @wpisowe
      .center
        .notification Tylko do 30 kwietnia brak wpisowego!

    .target Drodzy Rodzice!
    %p
      Witamy Was serdecznie w naszym edukacyjnym żłobku „Kubusiowy Raj”, mieszczącym się w malowniczej okolicy, w Bobrowcu, 5 km od Piaseczna. U nas każda mała istotka (od 5 miesiąca do 3 roku życia), równie dociekliwa jak Puchatek, otrzyma czas na
      %q powolne, uważne tropienie tego, co zadziwia, zastanawia, uczy, kształtuje, uwrażliwia, doskonali, stymuluje
      \ . Inspiracji do codziennego towarzyszenia Państwa Pociechom dostarcza nam Pedagogika M. Montessorii, która podkreśla, że ważną prośbą dzieci skierowaną do dorosłych jest zdanie
      %q Pomóż mi to zrobić samemu.
      Gorąco w to wierzymy i zamierzamy zaspokajać te dziecięce pragnienia.

    %blockquote.toright
      %p
        ! - A co tropisz? – zapytał Prosiaczek.<br>
        ! - Coś, coś, coś – odparł tajemniczo Puchatek.<br>
        ! - A co, co, co? – spytał Prosiaczek podchodząc bliżej.&nbsp;<br>(&hellip;)<br>
        ! - Będę musiał trochę poczekać, aż to coś wytropię, i wtedy się dowiem.
      %small
        / Kubuś Puchatek
        %cite{title: "lol"}Kubuś Puchatek i przyjaciele

      -# %p
        This is the home page for the
        <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
        sample application.

    %p Zapewniamy maluchom nie tylko całodzienną opieką, ale też zajęcia stymulujące  ich rozwój werbalny, psychoruchowy i emocjonalno-społeczny. Szanujemy  ich wewnętrzny potencjał, potrzeby rozwojowe, indywidualne predyspozycje i ciekawość poznawczą. Pozwalamy na eksplorację otaczającego świata w bezpiecznych warunkach, w atmosferze pełnej akceptacji, cierpliwości  i  życzliwości.
    %p Reasumując! My – wykwalifikowane wychowawczynie z pasji i powołania, z dziećmi nudzić się nie umiemy. Bawimy się, śmiejemy, uczymy się od siebie nawzajem i w atmosferze wzajemnego szacunku, uważności i empatii poznajemy siebie i  otaczający świat.
    %p Będzie nam bardzo miło, jeżeli po zapoznaniu się z działalnością naszego Żłobka, zechcecie Państwo przekazać swoje pociechy pod fachową opiekę naszego personelu.
    %p Ufamy, że prowadzona przez nas działalność w pełni sprosta Państwa oczekiwaniom.
    %p Mamy nadzieje, że wirtualne spotkanie z nami odpowie na pytania i odwiedzicie Państwo nasz żłobek osobiście. Szczerze Państwa i Państwa pociechy zapraszamy!
    %p
      W razie jakichwkolwiek pytań, prosimy o kontakt
      %span.inline(title="kom. 881 589 599") telefoniczny
      , mailowy
      %a.inline(href="biuro@zlobekkubusiowyraj.pl"
        title="biuro@zlobekkubuisowyraj.pl") biuro@zlobekkubusiowyraj.pl
      lub poprzez
      = succeed "." do
        = link_to "formularz kontaktowy",
          contact_us_path


    -# = link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/'